/*
OpenGL Shell - convenient OpenGL wrapper for use in OOP programs.
Copyright (C) 2005-2008 Victor Coda.

This library is free software; you can redistribute it and/or
modify it under the terms of the GNU Lesser General Public
License as published by the Free Software Foundation; either
version 2.1 of the License, or (at your option) any later version.

This library is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
Lesser General Public License for more details.

You should have received a copy of the GNU Lesser General Public
License along with this library. If not, see http://www.gnu.org/licenses

e-mail: bob.vilson@gmail.com
*/

// Τΰιλ: /GL/ContextCg.h
//

#ifdef _MSC_VER
#pragma once
#endif

#ifndef __GL_CONTEXT_CG_H__
#define __GL_CONTEXT_CG_H__

#ifdef CG_SDK

namespace GL
{
	//  A Cg context is a container for Cg programs. Each Cg context maintains a NULL-terminated string 
	//  containing warning and error messages generated by the Cg compiler, state managers and the like.
	
	class DLLAPI CCgContext
    {
        friend              CCgShader;
        friend              CCgShadingProgram;

    private:

	    //
		// Interface
        //

        static void         AddRef              ();
        static void         Release             ();

        static CGcontext    GetContext          ();
        static const char*  GetLastListing      ();

    private:

		//
		// Class members
		//

        static CGcontext    m_Context;
        static GLuint       m_RefCount;
	};
}

#endif // CG_SDK

#endif // __GL_CONTEXT_CG_H__